### ISSUE TITLE
getting error

### ISSUE THREAD

**Issue by itzharshit** [Th30neAnd0nly/TrackDown#43]
> TrackDown@1.0.0 start
> node index.js
/root/td/index.js:65
if(msg?.reply_to_message?.text=="🌐 Enter Your URL"){
       ^
SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47

**Comment by prateek-chaubey** [comment]
Which node version are you using.

**Comment by itzharshit** [comment]
> Which node version are you using.

v12.22.9

**Comment by prateek-chaubey** [comment]
Try using latest one such as v16 or v18

**Comment by itzharshit** [comment]
Now i am getting new error
```
 TrackDown@1.0.0 start
> node index.js
node:events:491
      throw er; // Unhandled 'error' event
      ^
Error: listen EPERM: operation not permitted 0.0.0.0:5000
    at Server.setupListenHandle [as _listen2] (node:net:1446:21)
    at listenInCluster (node:net:1511:12)
    at Server.listen (node:net:1599:7)
    at Function.listen (/usr/home/Harshit/domains/x.harshit.wtf/public_html/node_modules/express/lib/application.js:635:24)
    at Object.<anonymous> (/usr/home/Harshit/domains/x.harshit.wtf/public_html/index.js:239:5)
    at Module._compile (node:internal/modules/cjs/loader:1198:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
    at Module.load (node:internal/modules/cjs/loader:1076:32)
    at Function.Module._load (node:internal/modules/cjs/loader:911:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:22:47
Emitted 'error' event on Server instance at:
    at emitErrorNT (node:net:1490:8)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  code: 'EPERM',
  errno: -1,
  syscall: 'listen',
  address: '0.0.0.0',
  port: 5000
```
